# Generated by Django 6.0 on 2026-01-04 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='order_index',
        ),
        migrations.AddField(
            model_name='homework',
            name='tasks',
            field=models.ManyToManyField(related_name='homeworks', to='study.task'),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to='study.user'),
        ),
    ]
