# Generated by Django 6.0 on 2026-01-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_remove_course_created_by_remove_topic_order_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Лёгкий'), (2, 'Средний'), (3, 'Сложный')], default=1),
        ),
    ]
